spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: bdc
    password: bdc
    url: jdbc:mysql://127.0.0.1/springclooud_sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
env:
  test6
girl:
  name: matea
  age: 1801




